-- generated by TurtleScript write-lua-ops.js

local ops = {}

ops.byname = {
  ["PUSH_FRAME"] = 0,
  ["PUSH_LOCAL_FRAME"] = 1,
  ["PUSH_LITERAL"] = 2,
  ["NEW_OBJECT"] = 3,
  ["NEW_ARRAY"] = 4,
  ["NEW_FUNCTION"] = 5,
  ["GET_SLOT_DIRECT"] = 6,
  ["GET_SLOT_INDIRECT"] = 7,
  ["GET_SLOT_DIRECT_CHECK"] = 8,
  ["SET_SLOT_DIRECT"] = 9,
  ["SET_SLOT_INDIRECT"] = 10,
  ["INVOKE"] = 11,
  ["RETURN"] = 12,
  ["JMP"] = 13,
  ["JMP_UNLESS"] = 14,
  ["POP"] = 15,
  ["DUP"] = 16,
  ["DUP2"] = 17,
  ["OVER"] = 18,
  ["OVER2"] = 19,
  ["SWAP"] = 20,
  ["UN_NOT"] = 21,
  ["UN_MINUS"] = 22,
  ["UN_TYPEOF"] = 23,
  ["BI_EQ"] = 24,
  ["BI_GT"] = 25,
  ["BI_GTE"] = 26,
  ["BI_ADD"] = 27,
  ["BI_SUB"] = 28,
  ["BI_MUL"] = 29,
  ["BI_DIV"] = 30
}

ops.bynum = {}

-- invert byname into bynum, and combine both into root export
for name,val in pairs(ops.byname) do
  ops.bynum[val] = name
  ops[name] = val
end

return ops
