-- generated by TurtleScript write-lua-bytecode.js
local jsval = require("luaturtle.jsval")
local ifunc = require("luaturtle.ifunc")

local startup = {}

-- Populate the function and literal arrays with the precompiled
-- startup code, including the compiler and standard library.

startup.functions = {
  ifunc.Function:new{
    name = nil,
    id = 0,
    nargs = 0,
    max_stack = 2,
    bytecode = {
      1, 0,     -- 0: push_literal(0)
      1, 1,     -- 2: push_literal(1)
      26,       -- 4: bi_add
      11        -- 5: return
    }
  }
}
-- literals
startup.literals = {
  jsval.newNumber(1), -- 0
  jsval.newNumber(2) -- 1
}

return startup
